import requests

users = [
    {"first_name": "Olivia", "second_name": "Jimenez", "email": "user1@test.com", "password": "pass1"},
    {"first_name": "Emily", "second_name": "Johnson", "email": "user2@test.com", "password": "pass2"},
    {"first_name": "Michael", "second_name": "Williams", "email": "user3@test.com", "password": "pass3"},
    {"first_name": "Sarah", "second_name": "Brown", "email": "user4@test.com", "password": "pass4"},
    {"first_name": "David", "second_name": "Jones", "email": "user5@test.com", "password": "pass5"},
    {"first_name": "Jessica", "second_name": "Garcia", "email": "user6@test.com", "password": "pass6"},
    {"first_name": "Daniel", "second_name": "Miller", "email": "user7@test.com", "password": "pass7"},
    {"first_name": "Ashley", "second_name": "Davis", "email": "user8@test.com", "password": "pass8"},
    {"first_name": "Matthew", "second_name": "Rodriguez", "email": "user9@test.com", "password": "pass9"},
    {"first_name": "Amanda", "second_name": "Martinez", "email": "user10@test.com", "password": "pass10"},
    {"first_name": "James", "second_name": "Hernandez", "email": "user11@test.com", "password": "pass11"},
    {"first_name": "Jennifer", "second_name": "Lopez", "email": "user12@test.com", "password": "pass12"},
    {"first_name": "Christopher", "second_name": "Gonzalez", "email": "user13@test.com", "password": "pass13"},
    {"first_name": "Elizabeth", "second_name": "Wilson", "email": "user14@test.com", "password": "pass14"},
    {"first_name": "Joseph", "second_name": "Anderson", "email": "user15@test.com", "password": "pass15"},
    {"first_name": "Megan", "second_name": "Thomas", "email": "user16@test.com", "password": "pass16"},
    {"first_name": "Joshua", "second_name": "Taylor", "email": "user17@test.com", "password": "pass17"},
    {"first_name": "John", "second_name": "Smith", "email": "user@test.com", "password": "MarketplaceAPP"},
    {"first_name": "Lauren", "second_name": "Moore", "email": "user18@test.com", "password": "pass18"},
    {"first_name": "Andrew", "second_name": "Jackson", "email": "user19@test.com", "password": "pass19"},
    {"first_name": "Nicole", "second_name": "Martin", "email": "user20@test.com", "password": "pass20"},
    {"first_name": "Brandon", "second_name": "Lee", "email": "user21@test.com", "password": "pass21"},
    {"first_name": "Samantha", "second_name": "Perez", "email": "user22@test.com", "password": "pass22"},
    {"first_name": "Ryan", "second_name": "Thompson", "email": "user23@test.com", "password": "pass23"},
    {"first_name": "Stephanie", "second_name": "White", "email": "user24@test.com", "password": "pass24"},
    {"first_name": "Justin", "second_name": "Harris", "email": "user25@test.com", "password": "pass25"},
    {"first_name": "Rachel", "second_name": "Sanchez", "email": "user26@test.com", "password": "pass26"},
    {"first_name": "Anthony", "second_name": "Clark", "email": "user27@test.com", "password": "pass27"},
    {"first_name": "Heather", "second_name": "Ramirez", "email": "user28@test.com", "password": "pass28"},
    {"first_name": "Jonathan", "second_name": "Lewis", "email": "user29@test.com", "password": "pass29"},
    {"first_name": "Amber", "second_name": "Robinson", "email": "user30@test.com", "password": "pass30"},
    {"first_name": "Nicholas", "second_name": "Walker", "email": "user31@test.com", "password": "pass31"},
    {"first_name": "Danielle", "second_name": "Young", "email": "user32@test.com", "password": "pass32"},
    {"first_name": "Tyler", "second_name": "Allen", "email": "user33@test.com", "password": "pass33"},
    {"first_name": "Brittany", "second_name": "King", "email": "user34@test.com", "password": "pass34"},
    {"first_name": "Zachary", "second_name": "Wright", "email": "user35@test.com", "password": "pass35"},
    {"first_name": "Kayla", "second_name": "Scott", "email": "user36@test.com", "password": "pass36"},
    {"first_name": "Aaron", "second_name": "Torres", "email": "user37@test.com", "password": "pass37"},
    {"first_name": "Victoria", "second_name": "Nguyen", "email": "user38@test.com", "password": "pass38"},
    {"first_name": "Kevin", "second_name": "Hill", "email": "user39@test.com", "password": "pass39"},
    {"first_name": "Courtney", "second_name": "Flores", "email": "user40@test.com", "password": "pass40"},
    {"first_name": "Brian", "second_name": "Green", "email": "user41@test.com", "password": "pass41"},
    {"first_name": "Rebecca", "second_name": "Adams", "email": "user42@test.com", "password": "pass42"},
    {"first_name": "Eric", "second_name": "Nelson", "email": "user43@test.com", "password": "pass43"},
    {"first_name": "Laura", "second_name": "Baker", "email": "user44@test.com", "password": "pass44"},
    {"first_name": "Steven", "second_name": "Hall", "email": "user45@test.com", "password": "pass45"},
    {"first_name": "Kimberly", "second_name": "Rivera", "email": "user46@test.com", "password": "pass46"},
    {"first_name": "Timothy", "second_name": "Campbell", "email": "user47@test.com", "password": "pass47"},
    {"first_name": "Angela", "second_name": "Mitchell", "email": "user48@test.com", "password": "pass48"},
    {"first_name": "Jason", "second_name": "Carter", "email": "user49@test.com", "password": "pass49"},
    {"first_name": "Melissa", "second_name": "Roberts", "email": "user50@test.com", "password": "pass50"},
    {"first_name": "Jeffrey", "second_name": "Gomez", "email": "user51@test.com", "password": "pass51"},
    {"first_name": "Michelle", "second_name": "Phillips", "email": "user52@test.com", "password": "pass52"},
    {"first_name": "Gary", "second_name": "Evans", "email": "user53@test.com", "password": "pass53"},
    {"first_name": "Deborah", "second_name": "Turner", "email": "user54@test.com", "password": "pass54"},
    {"first_name": "Jacob", "second_name": "Diaz", "email": "user55@test.com", "password": "pass55"},
    {"first_name": "Amy", "second_name": "Parker", "email": "user56@test.com", "password": "pass56"},
    {"first_name": "Larry", "second_name": "Cruz", "email": "user57@test.com", "password": "pass57"},
    {"first_name": "Sharon", "second_name": "Edwards", "email": "user58@test.com", "password": "pass58"},
    {"first_name": "Frank", "second_name": "Collins", "email": "user59@test.com", "password": "pass59"},
    {"first_name": "Anna", "second_name": "Reyes", "email": "user60@test.com", "password": "pass60"},
    {"first_name": "Scott", "second_name": "Stewart", "email": "user61@test.com", "password": "pass61"},
    {"first_name": "Ruth", "second_name": "Morris", "email": "user62@test.com", "password": "pass62"},
    {"first_name": "Gregory", "second_name": "Morales", "email": "user63@test.com", "password": "pass63"},
    {"first_name": "Julie", "second_name": "Murphy", "email": "user64@test.com", "password": "pass64"},
    {"first_name": "Patrick", "second_name": "Cook", "email": "user65@test.com", "password": "pass65"},
    {"first_name": "Diane", "second_name": "Rogers", "email": "user66@test.com", "password": "pass66"},
    {"first_name": "Peter", "second_name": "Gutierrez", "email": "user67@test.com", "password": "pass67"},
    {"first_name": "Alice", "second_name": "Ortiz", "email": "user68@test.com", "password": "pass68"},
    {"first_name": "Dennis", "second_name": "Morgan", "email": "user69@test.com", "password": "pass69"},
    {"first_name": "Marie", "second_name": "Cooper", "email": "user70@test.com", "password": "pass70"},
    {"first_name": "Walter", "second_name": "Peterson", "email": "user71@test.com", "password": "pass71"},
    {"first_name": "Janet", "second_name": "Bailey", "email": "user72@test.com", "password": "pass72"},
    {"first_name": "Harold", "second_name": "Reed", "email": "user73@test.com", "password": "pass73"},
    {"first_name": "Catherine", "second_name": "Kelly", "email": "user74@test.com", "password": "pass74"},
    {"first_name": "Douglas", "second_name": "Howard", "email": "user75@test.com", "password": "pass75"},
    {"first_name": "Frances", "second_name": "Ramos", "email": "user76@test.com", "password": "pass76"},
    {"first_name": "Henry", "second_name": "Kim", "email": "user77@test.com", "password": "pass77"},
    {"first_name": "Christine", "second_name": "Cox", "email": "user78@test.com", "password": "pass78"},
    {"first_name": "Arthur", "second_name": "Ward", "email": "user79@test.com", "password": "pass79"},
    {"first_name": "Virginia", "second_name": "Richardson", "email": "user80@test.com", "password": "pass80"},
    {"first_name": "Carl", "second_name": "Watson", "email": "user81@test.com", "password": "pass81"},
    {"first_name": "Martha", "second_name": "Brooks", "email": "user82@test.com", "password": "pass82"},
    {"first_name": "Joe", "second_name": "Chavez", "email": "user83@test.com", "password": "pass83"},
    {"first_name": "Gloria", "second_name": "Wood", "email": "user84@test.com", "password": "pass84"},
    {"first_name": "Jack", "second_name": "James", "email": "user85@test.com", "password": "pass85"},
    {"first_name": "Teresa", "second_name": "Bennett", "email": "user86@test.com", "password": "pass86"},
    {"first_name": "Albert", "second_name": "Gray", "email": "user87@test.com", "password": "pass87"},
    {"first_name": "Sara", "second_name": "Mendoza", "email": "user88@test.com", "password": "pass88"},
    {"first_name": "Wayne", "second_name": "Ruiz", "email": "user89@test.com", "password": "pass89"},
    {"first_name": "Janice", "second_name": "Hughes", "email": "user90@test.com", "password": "pass90"},
    {"first_name": "Roy", "second_name": "Price", "email": "user91@test.com", "password": "pass91"},
    {"first_name": "Evelyn", "second_name": "Alvarez", "email": "user92@test.com", "password": "pass92"},
    {"first_name": "Ralph", "second_name": "Castillo", "email": "user93@test.com", "password": "pass93"},
    {"first_name": "Judith", "second_name": "Sanders", "email": "user94@test.com", "password": "pass94"},
    {"first_name": "Philip", "second_name": "Patel", "email": "user95@test.com", "password": "pass95"},
    {"first_name": "Cheryl", "second_name": "Myers", "email": "user96@test.com", "password": "pass96"},
    {"first_name": "Eugene", "second_name": "Long", "email": "user97@test.com", "password": "pass97"},
    {"first_name": "Hannah", "second_name": "Ross", "email": "user98@test.com", "password": "pass98"},
    {"first_name": "Martin", "second_name": "Foster", "email": "user99@test.com", "password": "pass99"},
]

for user in users:
    response = requests.post(
        "http://localhost:8000/users",
        json={
            "first_name": user["first_name"],
            "second_name": user["second_name"],
            "email": user["email"],
            "password": user["password"]
        }
    )
    print(f"{user['email']}: {response.status_code}")
