import requests

users = [
    {"first_name": "Olivia", "second_name": "Jimenez", "email": "user1@test.com", "password": "password1"},
    {"first_name": "Emily", "second_name": "Johnson", "email": "user2@test.com", "password": "password2"},
    {"first_name": "Michael", "second_name": "Williams", "email": "user3@test.com", "password": "password3"},
    {"first_name": "Sarah", "second_name": "Brown", "email": "user4@test.com", "password": "password4"},
    {"first_name": "David", "second_name": "Jones", "email": "user5@test.com", "password": "password5"},
    {"first_name": "Jessica", "second_name": "Garcia", "email": "user6@test.com", "password": "password6"},
    {"first_name": "Daniel", "second_name": "Miller", "email": "user7@test.com", "password": "password7"},
    {"first_name": "Ashley", "second_name": "Davis", "email": "user8@test.com", "password": "password8"},
    {"first_name": "Matthew", "second_name": "Rodriguez", "email": "user9@test.com", "password": "password9"},
    {"first_name": "Amanda", "second_name": "Martinez", "email": "user10@test.com", "password": "password10"},
    {"first_name": "James", "second_name": "Hernandez", "email": "user11@test.com", "password": "password11"},
    {"first_name": "Jennifer", "second_name": "Lopez", "email": "user12@test.com", "password": "password12"},
    {"first_name": "Christopher", "second_name": "Gonzalez", "email": "user13@test.com", "password": "password13"},
    {"first_name": "Elizabeth", "second_name": "Wilson", "email": "user14@test.com", "password": "password14"},
    {"first_name": "Joseph", "second_name": "Anderson", "email": "user15@test.com", "password": "password15"},
    {"first_name": "Megan", "second_name": "Thomas", "email": "user16@test.com", "password": "password16"},
    {"first_name": "Joshua", "second_name": "Taylor", "email": "user17@test.com", "password": "password17"},
    {"first_name": "John", "second_name": "Smith", "email": "user@test.com", "password": "MarketplaceAPI"},
    {"first_name": "Lauren", "second_name": "Moore", "email": "user18@test.com", "password": "password18"},
    {"first_name": "Andrew", "second_name": "Jackson", "email": "user19@test.com", "password": "password19"},
    {"first_name": "Nicole", "second_name": "Martin", "email": "user20@test.com", "password": "password20"},
    {"first_name": "Brandon", "second_name": "Lee", "email": "user21@test.com", "password": "password21"},
    {"first_name": "Samantha", "second_name": "Perez", "email": "user22@test.com", "password": "password22"},
    {"first_name": "Ryan", "second_name": "Thompson", "email": "user23@test.com", "password": "password23"},
    {"first_name": "Stephanie", "second_name": "White", "email": "user24@test.com", "password": "password24"},
    {"first_name": "Justin", "second_name": "Harris", "email": "user25@test.com", "password": "password25"},
    {"first_name": "Rachel", "second_name": "Sanchez", "email": "user26@test.com", "password": "password26"},
    {"first_name": "Anthony", "second_name": "Clark", "email": "user27@test.com", "password": "password27"},
    {"first_name": "Heather", "second_name": "Ramirez", "email": "user28@test.com", "password": "password28"},
    {"first_name": "Jonathan", "second_name": "Lewis", "email": "user29@test.com", "password": "password29"},
    {"first_name": "Amber", "second_name": "Robinson", "email": "user30@test.com", "password": "password30"},
    {"first_name": "Nicholas", "second_name": "Walker", "email": "user31@test.com", "password": "password31"},
    {"first_name": "Danielle", "second_name": "Young", "email": "user32@test.com", "password": "password32"},
    {"first_name": "Tyler", "second_name": "Allen", "email": "user33@test.com", "password": "password33"},
    {"first_name": "Brittany", "second_name": "King", "email": "user34@test.com", "password": "password34"},
    {"first_name": "Zachary", "second_name": "Wright", "email": "user35@test.com", "password": "password35"},
    {"first_name": "Kayla", "second_name": "Scott", "email": "user36@test.com", "password": "password36"},
    {"first_name": "Aaron", "second_name": "Torres", "email": "user37@test.com", "password": "password37"},
    {"first_name": "Victoria", "second_name": "Nguyen", "email": "user38@test.com", "password": "password38"},
    {"first_name": "Kevin", "second_name": "Hill", "email": "user39@test.com", "password": "password39"},
    {"first_name": "Courtney", "second_name": "Flores", "email": "user40@test.com", "password": "password40"},
    {"first_name": "Brian", "second_name": "Green", "email": "user41@test.com", "password": "password41"},
    {"first_name": "Rebecca", "second_name": "Adams", "email": "user42@test.com", "password": "password42"},
    {"first_name": "Eric", "second_name": "Nelson", "email": "user43@test.com", "password": "password43"},
    {"first_name": "Laura", "second_name": "Baker", "email": "user44@test.com", "password": "password44"},
    {"first_name": "Steven", "second_name": "Hall", "email": "user45@test.com", "password": "password45"},
    {"first_name": "Kimberly", "second_name": "Rivera", "email": "user46@test.com", "password": "password46"},
    {"first_name": "Timothy", "second_name": "Campbell", "email": "user47@test.com", "password": "password47"},
    {"first_name": "Angela", "second_name": "Mitchell", "email": "user48@test.com", "password": "password48"},
    {"first_name": "Jason", "second_name": "Carter", "email": "user49@test.com", "password": "password49"},
    {"first_name": "Melissa", "second_name": "Roberts", "email": "user50@test.com", "password": "password50"},
    {"first_name": "Jeffrey", "second_name": "Gomez", "email": "user51@test.com", "password": "password51"},
    {"first_name": "Michelle", "second_name": "Phillips", "email": "user52@test.com", "password": "password52"},
    {"first_name": "Gary", "second_name": "Evans", "email": "user53@test.com", "password": "password53"},
    {"first_name": "Deborah", "second_name": "Turner", "email": "user54@test.com", "password": "password54"},
    {"first_name": "Jacob", "second_name": "Diaz", "email": "user55@test.com", "password": "password55"},
    {"first_name": "Amy", "second_name": "Parker", "email": "user56@test.com", "password": "password56"},
    {"first_name": "Larry", "second_name": "Cruz", "email": "user57@test.com", "password": "password57"},
    {"first_name": "Sharon", "second_name": "Edwards", "email": "user58@test.com", "password": "password58"},
    {"first_name": "Frank", "second_name": "Collins", "email": "user59@test.com", "password": "password59"},
    {"first_name": "Anna", "second_name": "Reyes", "email": "user60@test.com", "password": "password60"},
    {"first_name": "Scott", "second_name": "Stewart", "email": "user61@test.com", "password": "password61"},
    {"first_name": "Ruth", "second_name": "Morris", "email": "user62@test.com", "password": "password62"},
    {"first_name": "Gregory", "second_name": "Morales", "email": "user63@test.com", "password": "password63"},
    {"first_name": "Julie", "second_name": "Murphy", "email": "user64@test.com", "password": "password64"},
    {"first_name": "Patrick", "second_name": "Cook", "email": "user65@test.com", "password": "password65"},
    {"first_name": "Diane", "second_name": "Rogers", "email": "user66@test.com", "password": "password66"},
    {"first_name": "Peter", "second_name": "Gutierrez", "email": "user67@test.com", "password": "password67"},
    {"first_name": "Alice", "second_name": "Ortiz", "email": "user68@test.com", "password": "password68"},
    {"first_name": "Dennis", "second_name": "Morgan", "email": "user69@test.com", "password": "password69"},
    {"first_name": "Marie", "second_name": "Cooper", "email": "user70@test.com", "password": "password70"},
    {"first_name": "Walter", "second_name": "Peterson", "email": "user71@test.com", "password": "password71"},
    {"first_name": "Janet", "second_name": "Bailey", "email": "user72@test.com", "password": "password72"},
    {"first_name": "Harold", "second_name": "Reed", "email": "user73@test.com", "password": "password73"},
    {"first_name": "Catherine", "second_name": "Kelly", "email": "user74@test.com", "password": "password74"},
    {"first_name": "Douglas", "second_name": "Howard", "email": "user75@test.com", "password": "password75"},
    {"first_name": "Frances", "second_name": "Ramos", "email": "user76@test.com", "password": "password76"},
    {"first_name": "Henry", "second_name": "Kim", "email": "user77@test.com", "password": "password77"},
    {"first_name": "Christine", "second_name": "Cox", "email": "user78@test.com", "password": "password78"},
    {"first_name": "Arthur", "second_name": "Ward", "email": "user79@test.com", "password": "password79"},
    {"first_name": "Virginia", "second_name": "Richardson", "email": "user80@test.com", "password": "password80"},
    {"first_name": "Carl", "second_name": "Watson", "email": "user81@test.com", "password": "password81"},
    {"first_name": "Martha", "second_name": "Brooks", "email": "user82@test.com", "password": "password82"},
    {"first_name": "Joe", "second_name": "Chavez", "email": "user83@test.com", "password": "password83"},
    {"first_name": "Gloria", "second_name": "Wood", "email": "user84@test.com", "password": "password84"},
    {"first_name": "Jack", "second_name": "James", "email": "user85@test.com", "password": "password85"},
    {"first_name": "Teresa", "second_name": "Bennett", "email": "user86@test.com", "password": "password86"},
    {"first_name": "Albert", "second_name": "Gray", "email": "user87@test.com", "password": "password87"},
    {"first_name": "Sara", "second_name": "Mendoza", "email": "user88@test.com", "password": "password88"},
    {"first_name": "Wayne", "second_name": "Ruiz", "email": "user89@test.com", "password": "password89"},
    {"first_name": "Janice", "second_name": "Hughes", "email": "user90@test.com", "password": "password90"},
    {"first_name": "Roy", "second_name": "Price", "email": "user91@test.com", "password": "password91"},
    {"first_name": "Evelyn", "second_name": "Alvarez", "email": "user92@test.com", "password": "password92"},
    {"first_name": "Ralph", "second_name": "Castillo", "email": "user93@test.com", "password": "password93"},
    {"first_name": "Judith", "second_name": "Sanders", "email": "user94@test.com", "password": "password94"},
    {"first_name": "Philip", "second_name": "Patel", "email": "user95@test.com", "password": "password95"},
    {"first_name": "Cheryl", "second_name": "Myers", "email": "user96@test.com", "password": "password96"},
    {"first_name": "Eugene", "second_name": "Long", "email": "user97@test.com", "password": "password97"},
    {"first_name": "Hannah", "second_name": "Ross", "email": "user98@test.com", "password": "password98"},
    {"first_name": "Martin", "second_name": "Foster", "email": "user99@test.com", "password": "password99"},
]

for user in users:
    response = requests.post(
        "http://localhost:8000/users",
        json={
            "first_name": user["first_name"],
            "second_name": user["second_name"],
            "email": user["email"],
            "password": user["password"]
        }
    )
    print(f"{user['email']}: {response.status_code}")
